test(specified_target): remove target_arch = "riscv64" cfg
and make they normal testcases.

`rustup target add riscv64gc-unknown-linux-gnu` is required to make
them pass.

If riscv64gc-unknown-linux-gnu is not installed, there will be errors:

command=`CARGO_BUILD_TARGET="riscv64gc-unknown-linux-gnu" "/home/zjp/rust/cargo-semver-checks/target/debug/cargo-semver-checks" "semver-checks" "check-release" "--manifest
-path=test_crates/template/new" "--baseline-root=test_crates/template/old"`
code=1
stdout=""
stderr=```
    Building template v0.1.0 (current)
error: running cargo-doc on crate \'template\' failed with output:
-----
    Blocking waiting for file lock on build directory
 Documenting template v0.1.0 (/home/zjp/rust/cargo-semver-checks/test_crates/template/new)
error[E0463]: can\'t find crate for `std`
  |
  = note: the `riscv64gc-unknown-linux-gnu` target may not be installed
  = help: consider downloading the target with `rustup target add riscv64gc-unknown-linux-gnu`
  = help: consider building the standard library from source with `cargo build -Zbuild-std`

For more information about this error, try `rustc --explain E0463`.
error: could not document `template`