test(specified_target): add with_{env_var,flag}_aarch64_unknown_none
Both testcases require `rustup target add x86_64-unknown-linux-gnu`.

But currently, cargo has a bug for learning target info:

command=`CARGO_BUILD_TARGET="aarch64-unknown-none" "/home/zjp/rust/cargo-semver-checks/target/debug/cargo-semver-checks" "semver-checks" "check-release" "--manifest-path=t
est_crates/template/new" "--baseline-root=test_crates/template/old"`
code=1
stdout=""
stderr=```
    Building template v0.1.0 (current)
error: running cargo-doc on crate \'template\' failed with output:
-----
error: output of --print=file-names missing when learning about target-specific information from rustc
command was: `/home/zjp/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rustc - --crate-name ___ --print=file-names --cap-lints=allow --target aarch64-unknown-none
 --crate-type bin --crate-type rlib --crate-type dylib --crate-type cdylib --crate-type staticlib --crate-type proc-macro --print=sysroot --print=split-debuginfo --print=c
rate-name --print=cfg`

--- stdout
___
lib___.rlib
lib___.a
/home/zjp/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu
off
___
debug_assertions
fmt_debug=\"full\"
overflow_checks
panic=\"abort\"
proc_macro
relocation_model=\"static\"
target_abi=\"\"
target_arch=\"aarch64\"
target_endian=\"little\"
target_env=\"\"
target_feature=\"neon\"
target_has_atomic
target_has_atomic=\"128\"
target_has_atomic=\"16\"
target_has_atomic=\"32\"
target_has_atomic=\"64\"
target_has_atomic=\"8\"
target_has_atomic=\"ptr\"
target_has_atomic_equal_alignment=\"128\"
target_has_atomic_equal_alignment=\"16\"
target_has_atomic_equal_alignment=\"32\"
target_has_atomic_equal_alignment=\"64\"
target_has_atomic_equal_alignment=\"8\"
target_has_atomic_equal_alignment=\"ptr\"
target_has_atomic_load_store
target_has_atomic_load_store=\"128\"
target_has_atomic_load_store=\"16\"
target_has_atomic_load_store=\"32\"
target_has_atomic_load_store=\"64\"
target_has_atomic_load_store=\"8\"
target_has_atomic_load_store=\"ptr\"
target_os=\"none\"
target_pointer_width=\"64\"
target_vendor=\"unknown\"
ub_checks

Hopefully, the fix from cargo will land in weekend.
Ref https://github.com/obi1kenobi/cargo-semver-checks/issues/1068#issuecomment-2581704041